'''This is my first attempt at making a mad libs style program from scratch
Created by: Thomas Chase
Created on: July 4, 2019'''
import time

#Greeting the user and asking their name
print("Hello welcome to 'Create your own Story'!")
name=input('What is your name?   ')
print('Welcome', name,'are you ready to start?')

#Here is were the user is asked for input to fill in the story
adjective_1=input('Please enter a descritption:')
color_1=input('Please enter an color: ')
name_1=input('Please enter a girls name: ')
name_2=input('Please enter another girls name: ')
name_3=input('Please enter an boys name: ')
activity_1=input('Please enter an activity: ')
length_of_time=input('Please enter a length of time: ')
season=input('Please enter a season: ')
political_office=input('Please enter a political office: ')
body_part=input('Please enter a body part: ')
city=input('Please enter a city: ')
item=input('Please enter an item: ')
cuss_word=input('Please enter a cuss word: ')

#Here is were the story is written
print('Once upom a time, a short time ago, in the town next store lived a',adjective_1,'girls who has long')
time.sleep(5)
print(color_1, 'hair that was considered the most beautiful in all the town')
time.sleep(5)
print('Her name was', name_1,'and everyone around knew her.')
time.sleep(5)
print('On hot afternoon while she was', activity_1,'when a new boy named', name_3,'moved in next door.')
time.sleep(5)
print('After about', length_of_time,'she began to wonder why he paid no attention to her.')
time.sleep(5)
print('Once school started again in', season,'she again saw the boy, but still it was as if she was invisable')
time.sleep(5)
print('This began to anger', name_1, 'so she asked her friend', name_2,' what she should do')
time.sleep(5)
print('"',name_2,'What should I do to get hime to notice me?!" said,', name_1,'.')
time.sleep(5)
print('"Introduce you self as the schools', political_office,'"replied', name_2,'.')
time.sleep(5)
print('"Great idea!" exclaimed', name_1,'.')
time.sleep(5)
print('So', name_1,'confidently walked up to the new boy and stuck our her', body_part,'.')
time.sleep(5)
print('"Hello! me name is', name_1,'and I am ', city,'high schools', political_office,', what is your name?"')
time.sleep(5)
print('"Ummmmmmmmmm, my name is', name_3,'".')
time.sleep(2)
print('"Well', name_3,'I have seen you around since you moved in. But you havent even so muched as looked at me. Why?" asked', name_1)
time.sleep(5)
print('"Oh, well you the first time I saw you I though you were beautiful. But every')
time.sleep(5)
print('time I am about to introduce myself you start makeing demon nosies. I didnt want to kill you')
time.sleep(5)
print('as my family and I are demon hunters" replied', name_3,'.')
time.sleep(5)
print('As', name_1,'soaked in what she had just heard,' ,name_3,'stood up and pulled out a', item,'.')
time.sleep(5)
print('',cuss_word,'yelled', name_1, 'You have discovered my secret!')
time.sleep(5)
print('THE END')
time.sleep(2)      
print("Thank you for playing my Mad Lib! Have a great day!")
time.sleep(10)
